Added Certificates API
opensearch-project/opensearch-api-specification pull request #112
Opened 2023-05-30 20:09 UTC by aabeshov

### Description
Added Certificates API

### Issues Resolved
[#106 ]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-01 01:27 UTC, nhtruong commented on model/plugins/get_certificates/operations.smithy
> +    "x-operation-group": "get_certificates",
remember to put this operation in `security` namepsace. Same with other operations.

2023-06-01 01:28 UTC, nhtruong commented on model/common_structures.smithy
> +}
This file will grown extremely large if we put every structure here. It's only meant for structure to be reused like the results of different types of search. Can we move these into the structures.smithy file of the respective operation?

2023-06-02 18:26 UTC, nhtruong approved these changes

2023-06-19 17:42 UTC, nhtruong approved these changes
Great work! 🚀

2023-06-19 20:19 UTC, VachaShah commented on model/security/get_certificates/operations.smithy
> +    "API Reference": "https://opensearch.org/docs/2.7/security/access-control/api/#get-certificates"
Lets use the latest version links for documentation rather than a specific version of OpenSearch.

2023-06-26 23:25 UTC, Xtansia requested changes

2023-06-26 23:25 UTC, Xtansia commented on model/security/get_certificates/structures.smithy
> +    certificateslist: CertificatesList
As can be seen [here](https://opensearch.org/docs/latest/security/access-control/api/#example-response-38), this should be:
```suggestion
    http_certificates_list: CertificatesList,
    transport_certificates_list: CertificatesList
```

2023-06-26 23:25 UTC, Xtansia commented on model/security/reload_http_certificates/operations.smithy
> +    "API Reference": "https://opensearch.org/docs/2.7/security/access-control/api/#reload-certificates"
```suggestion
    "API Reference": "https://opensearch.org/docs/latest/security/access-control/api/#reload-certificates"
```

2023-06-26 23:25 UTC, Xtansia commented on model/security/reload_transport_certificates/operations.smithy
> +    "API Reference": "https://opensearch.org/docs/2.7/security/access-control/api/#reload-certificates"
```suggestion
    "API Reference": "https://opensearch.org/docs/latest/security/access-control/api/#reload-certificates"
```

2023-06-26 23:25 UTC, Xtansia commented on model/security/get_certificates/operations.smithy
> +    "API Reference": "https://opensearch.org/docs/2.7/security/access-control/api/#get-certificates"
```suggestion
    "API Reference": "https://opensearch.org/docs/latest/security/access-control/api/#get-certificates"
```

2023-06-30 03:43 UTC, Xtansia approved these changes

2023-06-30 06:22 UTC, VachaShah approved these changes

2023-06-30 06:22 UTC, merged