Created and reworked branch from 'action_group_api'
opensearch-project/opensearch-api-specification pull request #134
Opened 2023-07-23 22:06 UTC by aabeshov

### Description
Created and reworked branch from 'action_group_api'

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-23 22:07 UTC, aabeshov commented
@Xtansia Hello, I can't solve problem that I can get through Build OpenAPI specs successfully.
This branch is synched with upstream/main branch, but when I add my api can't get pass test.

2023-07-23 22:22 UTC, Xtansia requested changes
Thanks for recreating this PR @aabeshov, build errors are just because of a mixup with the input/output structures for the PatchActionGroups operation

2023-07-23 22:22 UTC, Xtansia commented on model/opensearch.smithy
> -        SecurityHealth,
This shouldn't be being removed here

2023-07-23 22:22 UTC, Xtansia commented on model/security/action_group.smithy
> +}
This is not necessary.
```suggestion
```

2023-07-23 22:22 UTC, Xtansia commented on model/security/create_action_group/structures.smithy
> +    content: CreateActionGroupParams
The payload for the create action is just the resource structure itself.
```suggestion
    content: Action_Group
```

2023-07-23 22:22 UTC, Xtansia commented on model/security/patch_action_groups/structures.smithy
> +}
This is the cause of your build errors, it should contain the `PatchActionGroups` Input and Output shapes:
```suggestion

@input
structure PatchActionGroups_Input {
    @httpPayload
    content: PatchOperationList
}

@output
structure PatchActionGroups_Output {
    status: MessageStatus,
    message: Message
}
```

2023-07-23 22:33 UTC, aabeshov commented
@Xtansia Thank you very much for help.
Because when I was running ./gradlew build
Terminal gave me all the time some mistake with 'master_timeout' variables and I couldn't understand what's the problem.

2023-07-23 22:52 UTC, Xtansia approved these changes

2023-07-24 05:15 UTC, VachaShah approved these changes

2023-07-24 05:15 UTC, merged