Documenation b
opensearch-project/opensearch-api-specification pull request #136
Opened 2023-07-23 23:15 UTC by aabeshov

### Description
Added documentation to :
types 1(done)
cluster 21(done,less than half not found)
dangling 3(done)
indices 48 (done, almost half not found)
ingest 5 (done,1 not found)

### Issues Resolved
[#118]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-24 04:10 UTC, Xtansia requested changes
Looking good @aabeshov! Just a couple minor issues

2023-07-24 04:10 UTC, Xtansia commented on model/indices/stats/operations.smithy
> +    "API Reference": "https://opensearch.org/docs/latest/im-plugin/data-streams/"
This is not the correct URL for this API, I do not believe there's any info on the website docs about this one.

2023-07-24 04:10 UTC, Xtansia commented on model/indices/validate_query/operations.smithy
> +    "API Reference": "https://opensearch.org/docs/latest/observing-your-data/ad/api/#validate-detector"
This is not the correct url for this API. I do not believe there's a page on the website for this one.

2023-07-31 01:11 UTC, Xtansia approved these changes

2023-07-31 17:16 UTC, VachaShah approved these changes

2023-07-31 17:16 UTC, merged