Security/corrections
opensearch-project/opensearch-api-specification pull request #142
Opened 2023-08-11 20:37 UTC by nhtruong

### Description
A collection of small corrections for Security API spec.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-08-14 17:33 UTC, VachaShah approved these changes
LGTM!

2023-08-15 00:10 UTC, Xtansia requested changes
We should also change any operations using the `/_opendistro/_security/` path to instead be `/_plugins/_security/`

2023-08-15 00:10 UTC, Xtansia commented on model/security/update_all_distinguished_names/operations.smithy
> +operation UpdateAllDistinguishedNames {
I feel like for consistency this should be named `PatchDistinguishedNames` as with all other security plugin resources and configuration

2023-08-15 20:45 UTC, Xtansia approved these changes

2023-08-15 21:04 UTC, VachaShah approved these changes

2023-08-15 21:04 UTC, merged