Adds API spec coverage report.
opensearch-project/opensearch-api-specification pull request #179
Opened 2024-01-11 22:06 UTC by dblock

### Description

This report uses the API plugin POC in https://github.com/opensearch-project/OpenSearch/pull/11843 and [a tool](https://github.com/OpenAPITools/openapi-diff) to show the difference between OpenSearch 2.11 APIs and the OpenAPI spec checked into this repo. 

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-01-12 00:18 UTC, VachaShah reviewed
This is great! We now have a full list of APIs to be added in the specs. Thanks @dblock :) 

Does the "Legacy APIs" section mean the APIs that are deprecated?

2024-01-12 00:29 UTC, nhtruong approved these changes

2024-01-12 14:02 UTC, reta commented on .github/workflows/coverage.yml
> +          repository: 'dblock/OpenSearch'
@dblock we should probably merge that after https://github.com/opensearch-project/OpenSearch/pull/11843/files, right?

2024-01-17 17:24 UTC, dblock commented
@nhtruong @reta thanks for the review!

I plan to get https://github.com/opensearch-project/OpenSearch/pull/11876 in, move contents of https://github.com/opensearch-project/OpenSearch/pull/11843 into a new plugin (https://github.com/dblock/opensearch-api), publish that to Maven once 2.12 is released, and then use it from here. Stay tuned.

2024-01-23 15:34 UTC, dblock commented
Update: 

1. The supporting code got merged into OpenSearch via https://github.com/opensearch-project/OpenSearch/pull/11876.  
2. I re-extracted plugin code into https://github.com/dblock/opensearch-api.
3. This PR was updated to use OpenSearch 2.11.1 + 1 commit and the 2.x branch of opensearch-api.

2024-01-23 16:13 UTC, dblock commented
Coverage caught some minor discrepancies:

https://github.com/opensearch-project/opensearch-api-specification/pull/186
https://github.com/opensearch-project/security/pull/3976
https://github.com/opensearch-project/OpenSearch/pull/11992

2024-03-01 00:08 UTC, dblock commented
@Xtansia @nhtruong take a look, this is ready I think

2024-03-04 19:23 UTC, nhtruong submitted a review, later dismissed
LGTM

I assume that it would be very easy to switch over to comparing yaml specs right?

2024-03-04 21:33 UTC, dblock commented
> I assume that it would be very easy to switch over to comparing yaml specs right?

Looks like https://github.com/OpenAPITools/openapi-diff supports YAML. Might need some json/yaml foo for output.

2024-03-05 01:20 UTC, Xtansia requested changes

2024-03-05 01:20 UTC, Xtansia commented on .github/workflows/coverage.yml
> +          echo "API specs implemented for ${{ steps.coverage.outputs.current }}/${{ steps.coverage.outputs.total }} (${{ steps.math.outputs.percent }}%) APIs."
I would simplify this to a single script to save all the workflow interpolations (and remove the `$GITHUB_OUTPUT` step if not keeping the `add-pr-comment` step):
```suggestion
          current=`jq -r '.paths | keys | length' OpenSearch.openapi.json`
          total=`jq -r '.paths | keys | length' OpenSearch.auto.openapi.json`
          percent=$((current * 100 / total))
  
          cat >>"$GITHUB_OUTPUT" <<EOL
          current=$current
          total=$total
          percent=$percent
          EOL
  
          echo "API specs implemented for $current/$total ($percent%) APIs."
```

2024-03-05 16:14 UTC, dblock commented on .github/workflows/coverage.yml
> +      #       API specs implemented for ${{ steps.coverage.outputs.current }}/${{ steps.coverage.outputs.total }} (${{ steps.math.outputs.percent }}%) APIs.
The workflow needs permissions which are declared as part of this workflow for this to work. I'll delete it for now.

2024-03-05 16:15 UTC, dblock commented on .github/workflows/coverage.yml
> +          sleep 15
If you have a better way to wait for service I can change it.

2024-03-05 16:31 UTC, dblock commented
@Xtansia Thanks for a thorough review. Took all your suggestions, much simpler now.

2024-03-05 20:00 UTC, Xtansia approved these changes
Looks good 👍

2024-03-06 22:06 UTC, nhtruong approved these changes

2024-03-06 22:07 UTC, merged