Rollups API spec
opensearch-project/opensearch-api-specification pull request #283
Opened 2024-05-06 16:45 UTC by djmadeira

### Description
Add specs for rollup APIs

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-07 06:36 UTC, dblock requested changes
Thanks! Can you please sign DCO, `git commit -s --amend`.

2024-05-07 06:36 UTC, dblock commented on package-lock.json
> -}
Should we be running an `npm install` to lock dependencies? Or exclude this file in .gitignore. Either way probably a separate PR.

2024-05-07 13:41 UTC, djmadeira commented
@dblock done

2024-05-08 17:38 UTC, djmadeira commented
@dblock looks like it's passing now

2024-05-08 20:56 UTC, dblock commented
@nhtruong or @Xtansia take a look at the spec?

2024-05-09 15:50 UTC, nhtruong commented
This is great, Thanks @djmadeira
Regarding the `x-operation-group`, instead of `rollups.get_rollup`, `rollups.delete_rollup`... we should use `rollups.get`, `rollups.delete` instead to avoid repeating the world rollup as all of these actions are in the `rollups` namespace. We have a similar naming convention in the `indices` namespace with `indices.create`, `indices.delete` and so on.

2024-05-13 15:42 UTC, djmadeira commented
@nhtruong addressed feedback

2024-05-13 16:07 UTC, nhtruong commented
@djmadeira looks like some `x-operation-group` haven't not been updated. And there are 2 `transforms.get@200` entries and they caused some workflows to fail.

2024-05-13 17:13 UTC, djmadeira commented
@nhtruong looks like I got some wires crossed between the two PRs. fixed now.

2024-05-13 22:35 UTC, nhtruong approved these changes

2024-05-13 22:36 UTC, merged