Support outputs on tests
opensearch-project/opensearch-api-specification pull request #324
Opened 2024-06-06 23:59 UTC by miguel-vila

Adds a way to describe outputs in chapters, that can be used for later requests in the params or in the request bodies.

Added some unit tests and an integration test that uses this feature.

2024-06-07 12:10 UTC, dblock reviewed
This looks good! Rebase, add some to the documentation (DEVELOPER_GUIDE on writing tests probably). 

I suggest wrapping up the chapter output into a class and refactoring all the helper methods as class methods, it will make things a lot cleaner/better organized.

2024-06-07 12:10 UTC, dblock commented on tools/src/tester/helpers.ts
> +export function extract_output_values(response: ActualResponse, chapterOutput?: Output): EvaluationWithOutput {
Refactor into `ChapterOutput`, I think it should be constructed from `ActualResponse`, be a method on `ActualResponse`, or something like that.

2024-06-07 14:46 UTC, nhtruong commented on tools/src/tester/types/story.types.ts
> +
This file is not supposed to be edited by hand. It's generated from running `npx ts-node tools/src/tester/_generate_story_types.ts`.

The goal is maintaining parity between the JSON Schemas defined in `test_story.schema.yaml` and the TS types defined here.

2024-06-10 22:08 UTC, nhtruong requested changes

2024-06-10 22:08 UTC, nhtruong commented on tools/src/tester/StoryEvaluator.ts
> +import { check_story_variables, extract_output_values, overall_result } from './helpers'
If `check_story_variables` is only used here, it should be defined here instead.

2024-06-10 22:08 UTC, nhtruong commented on tools/src/tester/helpers.ts
> +    const error = check_used_variables(episode, story_outputs)
Isn't `story_ouputs` always `{}` in this case?

2024-06-10 22:16 UTC, nhtruong commented on tools/src/tester/StoryEvaluator.ts
> +    }
These errors should be assigned to the chapters that throw them so the view can pinpoint where to fix.

2024-06-10 22:17 UTC, nhtruong commented on tools/src/tester/ResultsDisplayer.ts
> +    const message = this.evaluation.message || this.evaluation.full_path
With [this](https://github.com/opensearch-project/opensearch-api-specification/pull/324/files/b0340fe5bdfac2013e63fa77cbf854b91ad16e31#r1633900477) we wont need this change anymore.

2024-06-11 12:19 UTC, dblock requested changes
@miguel-vila Let's get this merged? Iterate to green and say when you think you're done with the changes?

I don't love it that we're adding a ton of things to `helpers`, that's an OO anti-pattern. Consider refactoring those. Can also be refactired later.

2024-06-11 12:19 UTC, dblock commented on tools/src/tester/ChapterOutput.ts
> +  static create_dummy_from_output (output: Output): ChapterOutput {
Nit: this seems unnecessary, do `new ChapterOutput` where it's called?

2024-06-11 12:19 UTC, dblock commented on tools/src/tester/SupplementalChapterEvaluator.ts
> +        const output_values = extract_output_values(response)
This should read `response.output_values`, it's very business-logic specific to the reponse.

2024-06-11 12:19 UTC, dblock commented on tools/src/tester/ChapterEvaluator.ts
> +    const output_values = extract_output_values(response, chapter.output)
`extract_output_values` should either be a private method on `ChapterEvaluator` or maybe this works better as `chapter.output.extract_output_values_from_response(response)`?

2024-06-11 14:51 UTC, dblock commented on tools/tests/tester/start.test.ts
> +  expect(ChapterOutput.extract_output_values(response, output1)).toEqual(passed_output({
A `ChapterOutput` is something that is the result of an `Output` (a schema) and a response (values). I think the OO way should be closer to this:

```
new ChapterOutput(output, values)
```

2024-06-11 14:52 UTC, dblock approved these changes
@nhtruong take a look, I am good without all the refactors, can be done later

2024-06-11 16:04 UTC, nhtruong approved these changes

2024-06-11 16:04 UTC, merged