Add strict_allow_templates option for the dynamic mapping parameter
opensearch-project/opensearch-api-specification pull request #408
Opened 2024-07-11 06:05 UTC by gaobinlong

### Description

Add `strict_allow_templates` option for the dynamic mapping parameter, and remove the unsupported option `runtime`.

### Issues Resolved
[_List any issues this PR will resolve, e.g. Closes [...]._ ](https://github.com/opensearch-project/opensearch-api-specification/issues/407)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-11 06:15 UTC, gaobinlong commented
The code PR of `strict_allow_templates` will be released in 2.16.0, so do we need to do some version check in this repo?

2024-07-11 12:42 UTC, dblock requested changes
Please add a test into tests. You should be able to write one for the `runtime` change, but for the new parameter you'll need to run against a newer version of OpenSearch locally.

2024-07-11 12:42 UTC, dblock commented on CHANGELOG.md
> +- Add strict_allow_templates option for the dynamic mapping parameter ([#408](https://github.com/opensearch-project/opensearch-api-specification/pull/408))
Quote `strict_allow_templates`.

2024-07-11 12:42 UTC, dblock commented
> The code PR of `strict_allow_templates` will be released in 2.16.0, so do we need to do some version check in this repo?

Yes, this is https://github.com/opensearch-project/opensearch-api-specification/issues/398.

2024-07-17 09:43 UTC, gaobinlong commented
The failed test seems related to the env, the test case works well locally.
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/eb538727-240c-4390-b01a-2c14b4fbf9ac">

2024-07-17 12:59 UTC, dblock commented
> The failed test seems related to the env, the test case works well locally. <img alt="image" width="1170" src="https://private-user-images.githubusercontent.com/15811131/349449579-eb538727-240c-4390-b01a-2c14b4fbf9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjE0NTAsIm5iZiI6MTcyMTIyMTE1MCwicGF0aCI6Ii8xNTgxMTEzMS8zNDk0NDk1NzktZWI1Mzg3MjctMjQwYy00MzkwLWIwMWEtMmMxNGI0ZmJmOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDEyNTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NDE0NTZjNDE5Y2Y1YWQ1ZjFiNGM5ZGI0Nzc5MWNlOWU3ZWRhYTcyNTI4NzgyZGUxMzllNDkwNDA1YzZkMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rlh2LvBXVueiMFUCNrrMWXmA5KIfmh9Vy_XBXDvO73M">

I think 2.16 daily isn't starting, I'll look.

2024-07-23 11:59 UTC, dblock commented
Update CI to a newer 2.16 build that has your feature and it should all go 🟢 ?

https://github.com/opensearch-project/opensearch-api-specification/blob/main/.github/workflows/test-spec.yml#L29

2024-07-23 13:13 UTC, gaobinlong commented
> Update CI to a newer 2.16 build that has your feature and it should all go 🟢 ?
> 
> https://github.com/opensearch-project/opensearch-api-specification/blob/main/.github/workflows/test-spec.yml#L29

I think so.

2024-07-23 14:25 UTC, dblock commented
> > Update CI to a newer 2.16 build that has your feature and it should all go 🟢 ?
> > https://github.com/opensearch-project/opensearch-api-specification/blob/main/.github/workflows/test-spec.yml#L29
> 
> I think so.

I mean you can do it in this PR and we can merge.

2024-07-23 15:04 UTC, gaobinlong commented
@dblock I've updated the image version, now all checks have passed yet.

2024-07-23 16:02 UTC, merged

2024-07-23 16:03 UTC, dblock commented
If you want to do more, maybe move the template tests into a subfolder, so `tests/indices/mapping/dynamic.yaml` and add some more tests for other mapping options?

2024-07-24 02:12 UTC, gaobinlong commented
> If you want to do more, maybe move the template tests into a subfolder, so `tests/indices/mapping/dynamic.yaml` and add some more tests for other mapping options?

Sure, I'll do that later.