Replication namespace
opensearch-project/opensearch-api-specification pull request #464
Opened 2024-08-03 19:18 UTC by Tokesh

### Description
adding replication namespace specs

### Issues Resolved
[#232]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-03 21:09 UTC, dblock commented
Should we split the docker-compose.yml into docker-compose-default, docker-compose-multinode.yml or something like that?

2024-08-03 21:34 UTC, Tokesh commented
> Should we split the docker-compose.yml into docker-compose-default, docker-compose-multinode.yml or something like that?

Oh, do you work even on weekends? 
Yes, I encountered this today, tested it on a local machine. Now I was thinking of asking whether it is worth separating or inventing some flags.

2024-08-07 12:12 UTC, dblock commented
Take a look at https://github.com/opensearch-project/opensearch-api-specification/pull/472 that allows custom docker compose and tests.

2024-08-07 14:22 UTC, Tokesh commented
> Take a look at #472 that allows custom docker compose and tests.

Thank you! It looks really good
I'll wait for your PR to merge so I can continue working on the replication namespace.

2024-08-13 17:09 UTC, dblock commented
> > Take a look at #472 that allows custom docker compose and tests.
> 
> Thank you! It looks really good I'll wait for your PR to merge so I can continue working on the replication namespace.

@Tokesh that got merged FYI

2024-08-15 17:51 UTC, Tokesh commented
> > > Take a look at #472 that allows custom docker compose and tests.
> > 
> > 
> > Thank you! It looks really good I'll wait for your PR to merge so I can continue working on the replication namespace.
> 
> @Tokesh that got merged FYI

I have some problems with role mapping. Can you help me please? I got this
(Expected status 200, but received 403: application/json. No user found for indices:admin/plugins/replication/index/setup/validate)

2024-08-22 16:08 UTC, dblock commented
Want to finish this @Tokesh?

2024-09-04 15:32 UTC, Tokesh commented
> Want to finish this @Tokesh?

Oh, i didnt see your message. Actually, it works on my local computer. I'm still struggling with role mappings

2024-09-04 18:22 UTC, dblock commented
> > Want to finish this @Tokesh?
> 
> Oh, i didnt see your message. Actually, it works on my local computer. I'm still struggling with role mappings

LMK what kind of help you need? Rebase and I can help fix any failures here?

2024-09-05 20:18 UTC, Tokesh commented
> LMK what kind of help you need? Rebase and I can help fix any failures here?

Yeap, if it's possible please!

When I did everything locally, I did not encounter such problems. Perhaps I missed something somewhere. Perhaps I do not act on the admin side, but I tested different hypotheses. I will be glad if you help me. I tried to send you the documentation, perhaps I read something wrong.

refs:
[*Link*](https://opensearch.org/docs/latest/tuning-your-cluster/replication-plugin/permissions/)

2024-09-05 20:29 UTC, dblock commented
@Tokesh For the linter run `npm run lint--fix`, see what comes out?

The errors in the tests seem pretty straightforward:

```
ERROR   RESPONSE STATUS (Expected status 200, but received 403: application/json. No user found for indices:admin/plugins/replication/index/setup/validate)
```

Sounds like something that exists in your instance but not in a clean setup? You can always `docker system prune` and see if you can reproduce?

2024-11-08 19:05 UTC, Tokesh commented
> @Tokesh want to finish this?

Hi! I have quite a lot of work at my main job right now. If I can, I'll try to solve this PR on the weekend. If not, then it's worth closing or someone else should finish it if there are people interested. I couldn't do it myself when I was writing tests for CI/CD

2024-11-10 18:32 UTC, Tokesh commented
> @Tokesh want to finish this?

I passed the biggest part of CI/CD. 
Any suggestions to refactor this code?

2024-11-11 13:08 UTC, dblock submitted a review, later dismissed
This looks great!

I added .yml files to Vale preprocessing in https://github.com/opensearch-project/opensearch-api-specification/pull/660, let's rebase this once it's merged to make sure it worked.

2024-11-11 13:12 UTC, dblock commented on .github/workflows/test-spec.yml
> +
Get rid of the extra spaces.

2024-11-11 16:02 UTC, Tokesh commented on tests/plugins/replication/replica.yaml
> +$schema: ../../../json_schemas/test_story.schema.yaml
I think i can divide to:
```replica.yaml```
```stats.yaml```
```autofollow.yaml```
```replica-rules.yaml```
And the code will be duplicated everywhere where we create an index and start replicating it, if it works, then I can divide it like this and do it in a few days.

2024-11-11 16:58 UTC, dblock commented on tests/plugins/replication/replica.yaml
> +$schema: ../../../json_schemas/test_story.schema.yaml
That works. Maybe rename replica.yaml to index.yaml, that one will have the replication as the main act.

2024-11-17 13:23 UTC, Tokesh commented
Ready for your review! @dblock @nhtruong

2024-11-17 15:58 UTC, dblock requested changes
Glad we have a passing build!

Go through the fields and check whether they are semantically meaningful and need to be a `$ref` to something that exists (time values, index names, etc.).

2024-11-17 15:58 UTC, dblock commented on .github/workflows/test-spec.yml
> +          - version: 2.16.0
```suggestion
          - version: 2.18.0
```

Let's just use the latest, update 2.16 here to 2.18 and remove 2.17.

2024-11-17 15:58 UTC, dblock commented on spec/namespaces/replication.yaml
> +                type: boolean
Use a `$ref` to `AcknowledgedResponseBase`,  https://github.com/opensearch-project/opensearch-api-specification/blob/bf356019ed3450d97fb4f9f68be4db86d1ed2195/spec/schemas/_common.yaml#L14

2024-11-17 15:58 UTC, dblock commented on spec/schemas/replication._common.yaml
> +          type: string
Is this a known enum? If so it should be one.

2024-11-17 15:58 UTC, dblock commented on spec/schemas/replication._common.yaml
> +          type: string
If this is an index name it should be a ref.

2024-11-17 15:58 UTC, dblock commented on spec/schemas/replication._common.yaml
> +          type: integer
Should be 

```
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
```

2024-11-17 15:58 UTC, dblock commented on spec/schemas/replication._common.yaml
> +        total_read_time_lucene_millis:
Time values in ms are typically 

```
$ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitMillis'
```

2024-11-17 15:58 UTC, dblock commented on spec/schemas/replication._common.yaml
> +        translog_size_bytes:
Use a ref.

2024-11-17 23:27 UTC, dblock requested changes
Small one left, the rest LGTM!

2024-11-17 23:27 UTC, dblock commented on spec/schemas/replication._common.yaml
> +          anyOf:
Is this a combination of `SettingsBody` and these? So should be `allOf`.

2024-11-18 13:54 UTC, dblock approved these changes

2024-11-18 13:54 UTC, merged

2024-11-18 13:55 UTC, dblock commented
I made the change I suggested above and merged, thank you, this is great work @Tokesh!

2024-11-19 16:53 UTC, Tokesh commented
Oh, i just checked. Thank you so much for detailed reviews and help! It's a pleasure working with you!