Added rest_total_hits_as_int test for _search
opensearch-project/opensearch-api-specification pull request #466
Opened 2024-08-05 12:31 UTC by awick

### Description
Added simple search endpoint with rest_total_hits_as_int tests

### Issues Resolved

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-05 13:12 UTC, dblock requested changes
Looks good. Needs a rebase and some periods :)

2024-08-05 13:12 UTC, dblock commented on tests/_core/search/rest_total_hits_as_int.yaml
> +description: Test search endpoint with rest_total_hits_as_int
Add a period. I started adding a linter in https://github.com/opensearch-project/opensearch-api-specification/pull/463.

2024-08-05 13:12 UTC, dblock commented on tests/_core/search/rest_total_hits_as_int.yaml
> +  - synopsis: Search with rest_total_hits_as_int=true
Period.

2024-08-05 13:12 UTC, dblock commented on CHANGELOG.md
> +- Added `rest_total_hits_as_int` ([#466](https://github.com/opensearch-project/opensearch-api-specification/pull/466))
This is just tests, no spec changes, remove this.

2024-08-05 15:40 UTC, dblock commented
It thinks `Refn` is a word and tries to spell-check it, add to .cspell or rename the movie.

2024-08-05 15:54 UTC, dblock approved these changes

2024-08-05 15:57 UTC, merged

2024-08-08 19:41 UTC, dblock commented
@awick I have this intermittently failing in some environments, I think the results need a sort. For now I'll reduce this to 1 record in #483.

2024-08-09 11:30 UTC, awick commented
@dblock ok, the point of the 2 was to make sure track_total_hits was being honored and passed thru, when I get a chance I'll add the sort.