Asynchronous search namespace
opensearch-project/opensearch-api-specification pull request #525
Opened 2024-08-22 18:10 UTC by Tokesh

### Description
`asynchronous_search` namespace

### Issues Resolved
[#223]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-22 18:55 UTC, dblock requested changes
Looks good, I have a few nits.

2024-08-22 18:55 UTC, dblock commented on .github/workflows/test-spec.yml
> +            --opensearch-insecure --verbose \
Let's either remove `--verbose` or put it on its own line.

2024-08-22 18:55 UTC, dblock commented on CHANGELOG.md
> +- Added `asynchronous_search` namespace API specifications ([#525](https://github.com/opensearch-project/opensearch-api-specification/pull/525))
```suggestion
- Added `asynchronous_search` ([#525](https://github.com/opensearch-project/opensearch-api-specification/pull/525))
```

2024-08-22 18:55 UTC, dblock commented on tests/default/asynchronous_search/search.yaml
> +  - path: /{index}/_refresh
Nit: I think `_bulk` supports `refresh` as well if you want to collapse.

2024-08-22 18:55 UTC, dblock commented on tests/default/asynchronous_search/search.yaml
> +  - synopsis: Get partial response from asynchronous search.
So is it possible it hasn't completed yet (are we introducing a flaky test)?

2024-08-22 18:57 UTC, Tokesh commented
Hello everyone! 
I added asynchronous search to the specs, wrote a couple of tests. I noticed that in OS 3.0 they do not pass the tests, can you tell me why this might be. With other versions these tests pass successfully
I didn't find a word about removing asynchronous search in OS 3.0.
@dblock @nhtruong

2024-08-22 23:00 UTC, dblock commented
> Hello everyone! I added asynchronous search to the specs, wrote a couple of tests. I noticed that in OS 3.0 they do not pass the tests, can you tell me why this might be. With other versions these tests pass successfully I didn't find a word about removing asynchronous search in OS 3.0. @dblock @nhtruong

It looks like asynchronous search tests failed with the following:

```

[INFO] => POST /_plugins/_asynchronous_search ({
  "index": "books",
  "keep_on_completion": true
}) [application/json] {
  "query": {
    "match": {
      "author": {
        "query": "Bennett Miller"
      }
    }
  }
}
[INFO] <= 400 (application/json) | "no handler found for uri [/_plugins/_asynchronous_search] and method [POST]"
[INFO] => DELETE /books ({}) [application/json] 
[INFO] <= 200 (application/json; charset=UTF-8) | {
  "acknowledged": true
}
```

This means that the plugin is not in this 3.0 build (3.0 builds can be partial). Look for a newer tag on https://hub.docker.com/r/opensearchstaging/opensearch/tags that includes the asynchronous-search plugin as well and replace it in CI (might need to try locally).

2024-08-23 16:25 UTC, Tokesh commented
> This means that the plugin is not in this 3.0 build (3.0 builds can be partial). Look for a [newer tag](https://hub.docker.com/layers/opensearchstaging/opensearch/3.0.0/images/sha256-ec7b9f5edabec15412e2e4d58268d0e40d900c57bb59fa62a09e41b991d0f596?context=explore) on https://hub.docker.com/r/opensearchstaging/opensearch/tags that includes the asynchronous-search plugin as well and replace it in CI (might need to try locally).

I tried to use newer tag in 3.0 build, still same error. Can you check it? I guess I made a mistake somewhere
![image](https://github.com/user-attachments/assets/6fdfc48a-91b1-4597-9664-097a69e46ee3)

2024-08-23 16:59 UTC, dblock commented
@Tokesh I don't think it's a mistake, this likely means that asynchronous-search doesn't build in 3.0, and isn't included in any of these builds on docker hub 

@peterzhuamazon Can you help? How can one know which 3.0 build has asynchronous-search?

2024-08-23 17:04 UTC, dblock commented
@Tokesh For now add `< 3.0` to skip this test so we can merge this code?

2024-08-23 19:39 UTC, Tokesh commented
> @Tokesh I don't think it's a mistake, this likely means that asynchronous-search doesn't build in 3.0, and isn't included in any of these builds on docker hub
> 
> @peterzhuamazon Can you help? How can one know which 3.0 build has asynchronous-search?

Actually, i made a quick research about this situation.
I found `async_search` in OS 3.0 build [here](https://github.com/opensearch-project/asynchronous-search/issues/502)
But I don't know why it doesn't work now.

2024-08-23 19:40 UTC, Tokesh commented
> @Tokesh For now add `< 3.0` to skip this test so we can merge this code?

Ready for your review :)

2024-08-24 00:10 UTC, dblock commented
> Actually, i made a quick research about this situation. I found `async_search` in OS 3.0 build [here](https://github.com/opensearch-project/asynchronous-search/issues/502) But I don't know why it doesn't work now. I have hypothesis, that it shouldn't work like this

Will you take a look at this? It should work in 3.0 the same as in 2.x, or it's a bug.

2024-08-24 00:10 UTC, dblock approved these changes

2024-08-24 00:11 UTC, merged

2024-08-25 17:13 UTC, Tokesh commented
> > Actually, i made a quick research about this situation. I found `async_search` in OS 3.0 build [here](https://github.com/opensearch-project/asynchronous-search/issues/502) But I don't know why it doesn't work now. I have hypothesis, that it shouldn't work like this
> 
> Will you please take a look at this? At least open a bug. It should work in 3.0 the same as in 2.x, or it's a bug.

Yeap sure! I'm already opened issue in async-search repo.

2024-08-25 20:43 UTC, dblock commented
> Yeap sure! I'm already opened issue in async-search repo.

Thanks. That repo could use help if you want to try fixing it!