Update `TermsQuery` and TermsSetQuery and add tests
opensearch-project/opensearch-api-specification pull request #546
Opened 2024-08-30 22:53 UTC by prudhvigodithi

### Description

- Created schema for `Terms`.
- Updated `TermsQuery` and `TermsSetQuery` to use the `Terms` schema.
- Add unit tests for `TermsQuery` and `TermsSetQuery`.

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-api-specification/issues/540

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-31 01:12 UTC, dblock requested changes
Nice!

I think we should rename and organize the .yaml test filenames into folders consistently with the keywords used.

- `tests/default/_core/search/terms_query_field.yaml` is a `query` with `terms`, so   `tests/default/_core/search/query/terms.yaml`
- `terms_query_multiple` is a variation of the first one, so you should combine them
- `terms_set_query` is a query with `terms_set`, so it becomes `query/terms_set.yaml`

Generally we're not testing OpenSearch, just the schema. No need to test response bodies.

Finally, we also plan to use these tests to auto-generate documentation, so consistency becomes important (too many docs are all over the place when it comes to kinds of examples) - try to simplify these tests as much as possible. Try only using our canoical `movies` and `games` examples used elsewhere instead of introducing new types of things (classes, students). 

I have some more nitpicky comments, see which ones make sense to you.

2024-08-31 01:12 UTC, dblock commented on tests/default/_core/search/terms_query_field.yaml
> +    status: [201]
A lot of this can be replaced with a much shorter version with `_bulk`. Look for it in other tests.

2024-08-31 01:12 UTC, dblock commented on tests/default/_core/search/terms_query_multiple.yaml
> +            genre: [Adventure,Animation]
```suggestion
            genre:
              - adventure
              - animation
```

2024-08-31 01:12 UTC, dblock commented on tests/default/_core/search/terms_set_query.yaml
> +              _score: 0.5013843
We're not testing OpenSearch itself in this project, just the schema. I recommend leaving the minimum that ensures the response has something relevant to the query.

2024-09-03 17:02 UTC, prudhvigodithi commented
Thanks @dblock I have updated the PR addressing your comments, please take a look.

2024-09-03 17:45 UTC, dblock requested changes
Tiny nit of `,<space>`.

2024-09-03 17:45 UTC, dblock commented on tests/default/_core/search/query/terms.yaml
> +  # Setup for movies index with all necessary fields
I don't think this comment adds much value. I would remove them all.

2024-09-03 17:45 UTC, dblock commented on tests/default/_core/search/query/terms_set.yaml
> +        genres: [Adventure,Animation, Family]
```suggestion
        genres: [Adventure, Animation, Family]
```

I am surprised the linter isn't catching it. You can also put them all on their own lines if you wish.

2024-09-03 17:45 UTC, dblock commented on tests/default/_core/search/query/terms_set.yaml
> +              terms: [Adventure,Animation, Family]
```suggestion
              terms: [Adventure, Animation, Family]
```

2024-09-03 17:50 UTC, prudhvigodithi commented
Updated @dblock, please check.

2024-09-03 18:00 UTC, dblock approved these changes
👏

2024-09-03 18:00 UTC, merged

2024-09-03 18:00 UTC, dblock commented
If you're looking for more work @prudhvigodithi, https://github.com/opensearch-project/opensearch-api-specification/issues/548 looks like it's a bit more involved, might also need doc fixes.

2024-09-03 18:03 UTC, prudhvigodithi commented
Sure @dblock.
Thanks
@getsaurabh02