Add test about nested aggregation
opensearch-project/opensearch-api-specification pull request #576
Opened 2024-09-14 10:27 UTC by kkewwei

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-14 15:47 UTC, dblock requested changes
Thanks!

Looks like tests failed on 2.0, possibly because the feature wasn't there, so the test needs to be annotated accordingly.

Run `npm run lint--fix` for the linter to be happy.

I have some more nitpicks below.

2024-09-14 15:47 UTC, dblock commented on CHANGELOG.md
> +- Add test about nested aggregation ([#576](https://github.com/opensearch-project/opensearch-api-specification/issues/576))
No need to include a CHANGELOG for tests.

2024-09-14 15:47 UTC, dblock commented on tests/default/_core/aggregation/nested.yaml
> +$schema: ../../../../json_schemas/test_story.schema.yaml
Let's map the file name to the query, so this should be `search/aggs/nested_agg.yaml`.

2024-09-14 15:47 UTC, dblock commented on tests/default/_core/aggregation/nested.yaml
> +description: Test aggregation endpoints with nested.
I'll nitpick, there's no such a thing as aggregation endpoint. 

```suggestion
description: Test aggregation.
```

2024-09-14 15:47 UTC, dblock commented on tests/default/_core/aggregation/nested.yaml
> +  - synopsis: Bulk document.
Should go into prologue.

2024-09-14 15:47 UTC, dblock commented on tests/default/_core/aggregation/nested.yaml
> +                b1:
We plan to use these examples in the documentation. Is there some realistic agg scenario with movies? Maybe actors or something that would differentiate keywords like `nested` from data like `movie`.

2024-09-16 05:42 UTC, dblock requested changes
Some tests against 2.x failed, probably needs a `version: ` somewhere.

2024-09-16 05:42 UTC, dblock commented on tests/default/_core/search/aggs/nested_agg.yaml
> +        - {index: {_index: user_infos, _id: '0'}}
Could we keep with the theme of movies and books? We plan to use these in the documentation, trying to be a bit more consistent.

2024-09-16 16:37 UTC, dblock commented
```
ERROR   _core/search/aggs/nested_agg.yaml (Invalid Story: data/prologues/0 contains unsupported properties: request_body, request_body, request_body --- data/chapters/0/synopsis must match pattern "^\p{Lu}[\s\S]*\.$")
```

It's `request/payload`.

2024-09-17 02:49 UTC, kkewwei commented
@dblock  Thank you for your patient review, I'm not familiar with `opensearch-api-specification`, Is there any command I can use to test the change?  `npm run test` is ok?

2024-09-17 07:25 UTC, dblock commented
> @dblock Thank you for your patient review, I'm not familiar with `opensearch-api-specification`, Is there any command I can use to test the change? `npm run test` is ok?

Yes, do take a moment to read https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md and https://github.com/opensearch-project/opensearch-api-specification/blob/main/TESTING_GUIDE.md. I know it's a lot. 

We test an entire matrix of versions of OpenSearch, the 2.0 tests are failing. If you want to run those locally, it's basically starting a container with `OPENSEARCH_VERSION=2.0.0 docker compose up` from `tests/default` and then running tests with `OPENSEARCH_PASSWORD=admin npm run test:spec`.

2024-09-20 04:24 UTC, kkewwei commented
@dblock sorry for the latency reply(a bit busy), I will continue to follow up now.

2024-09-20 17:02 UTC, dblock requested changes
Thanks! LMK when it's ready to be reviewed.

Some of this should work in 2.17, right?

2024-09-21 14:11 UTC, kkewwei commented
> Thanks! LMK when it's ready to be reviewed.
> 
> Some of this should work in 2.17, right?

@dblock thanks for you help, I know how to test.

When I test the aggregation, it throws the exception:
```
            FAILED  RESPONSE PAYLOAD SCHEMA (data/aggregations/title MUST contain the missing properties: value, values, values, values, values, values, value, value, value, value, value, value, value, value, value, value, keys, avg, count, max, min, sum, avg, count, max, min, sum, avg, count, max, m, ...)
```
It seems that I should define the response schema of the aggregation, I try a long time to define user-input `aggs1` but fails, can you help adding a example aggregation test, and let me learn?
![image](https://github.com/user-attachments/assets/e0393b99-4cf7-47b8-a8cb-eecf8bb82549)

2024-09-23 15:07 UTC, dblock commented
Given the search response:

```
    search@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/_core.search.yaml#/components/schemas/ResponseBody'
```

it's a `ResponseBody` which defines `aggregations:`.

```
        aggregations:
          type: object
          additionalProperties:
            $ref: '_common.aggregations.yaml#/components/schemas/Aggregate'
```

if we replace this with just a vanilla object with any property (`additionalProperties: true`) the test will pass, so we're in the right place.

```
        aggregations:
          type: object
          additionalProperties: true
          # additionalProperties:
          #   $ref: '_common.aggregations.yaml#/components/schemas/Aggregate'
```

An `Aggregate` is one of many things:

```
    Aggregate:
      oneOf:
        - $ref: '#/components/schemas/CardinalityAggregate'
        - $ref: '#/components/schemas/HdrPercentilesAggregate'
        - ...
```

If we make the aggregate match our return value the spec also passes.

```
    Aggregate:
      oneOf:
        - type: object
          properties:
            doc_count:
              type: number
```

But if we add the other possibilities, it fails!

```
      oneOf:
        - type: object
          properties:
            doc_count:
              type: number
        - $ref: '#/components/schemas/CardinalityAggregate'
        - $ref: '#/components/schemas/HdrPercentilesAggregate'
```

This is where I've had a :facepalm: moment multiple times. Turns out that `oneOf` behaves like "only one of", not "any one of", so if more than one aggregate type matches, it will fail. And the schema validator is not smart enough to say "your object matches N items, but expected to only match 1".

The fix is to change `oneOf` by `anyOf`.

```
    Aggregate:
      anyOf:
        - $ref: '#/components/schemas/CardinalityAggregate'
        - $ref: '#/components/schemas/HdrPercentilesAggregate'
```

Note that each aggregation correctly uses `allOf`, combining `aggregateBase` and other properties of a specific aggregation. For example:

```
    PercentilesAggregateBase:
      allOf:
        - $ref: '#/components/schemas/AggregateBase'
        - type: object
          properties:
            values:
              $ref: '#/components/schemas/Percentiles'
          required:
            - values
```

https://github.com/dblock/opensearch-api-specification/commit/e497deadb4d4e13e6c0aa951382b4364698f7216

Rebase, then merge https://github.com/dblock/opensearch-api-specification/tree/kkewwei-add_nested_aggs onto your branch? I was on a plane and added some more agg tests on top.

2024-09-29 14:29 UTC, dblock approved these changes

2024-09-29 14:30 UTC, dblock requested changes
Let's add a 1-liner to CHANGELOG, maybe "Fix `/{index}/_search` with `aggregations`"?

Link checker is failing not sure how to fix that ... unrelated but if you have an idea include that.

2024-09-29 16:03 UTC, kkewwei commented
"Link checker is failing" seems to be a probabilistic problem, I have no idea how to fix it.

2024-09-29 16:37 UTC, dblock approved these changes

2024-09-29 16:37 UTC, merged