Added  `_ml/agents` and `ml/connectors`  specs
opensearch-project/opensearch-api-specification pull request #585
Opened 2024-09-18 20:16 UTC by junweid62

### Description
This PR documents a subset of the ML Commons APIs consumed by the Flow Framework client.

**Previously covered API specs (in other PRs):**
- `POST  /_plugins/_ml/model_groups/_register`
- `POST  /_plugins/_ml/models/_register`
- `DELETE  /_plugins/_ml/models/{model_id}`
- `POST /_plugins/_ml/models/{model_id}/_deploy`
- `POST /_plugins/_ml/models/{model_id}/_undeploy`

**New API specs added in this PR:**
- `POST  /_plugins/_ml/agents/_register`
- `DELETE  /_plugins/_ml/agents/{agent_id}`
- `POST  /_plugins/_ml/connectors/_create`
- `DELETE  /_plugins/_ml/connectors/{connector_id}`

### Issues Resolved
Part of #228 
Task 3 of [#833](https://github.com/opensearch-project/flow-framework/issues/833)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-19 05:48 UTC, dbwiddis approved these changes
LGTM from an API standpoint!

2024-09-19 05:48 UTC, dbwiddis commented on spec/schemas/ml._common.yaml
> +        - version
This is exactly the data we're going to want to pull programmatically to validate our templates.  Glad to see it being added!

2024-09-19 08:09 UTC, dblock requested changes
LGTM, small stuff for the broken link in CHANGELOG (missing a `)`).

2024-09-19 08:09 UTC, dblock commented on CHANGELOG.md
> -
Re-add this empty line below.

2024-09-19 08:09 UTC, dblock commented on CHANGELOG.md
> +- Added `/_plugins/_ml/agents/_register`, `/_plugins/_ml/connectors/_create`, `DELETE /_plugins/_ml/agents/{agent_id}`, `DELETE /_plugins/_ml/connectors/{connector_id}`([#228](https://github.com/open
```suggestion
- Added `/_plugins/_ml/agents/_register`, `/_plugins/_ml/connectors/_create`, `DELETE /_plugins/_ml/agents/{agent_id}`, `DELETE /_plugins/_ml/connectors/{connector_id}` ([#228](https://github.com/opensearch-project/opensearch-api-specification/issues/228))
```

2024-09-20 17:00 UTC, dblock approved these changes

2024-09-20 17:00 UTC, merged