add workload management querygroup api specs
opensearch-project/opensearch-api-specification pull request #649
Opened 2024-10-29 23:13 UTC by ruai0511

### Description
API spec for workload management, more specifically, for the query group lifecycle APIs.
Related PR: https://github.com/opensearch-project/OpenSearch/pull/14680, https://github.com/opensearch-project/OpenSearch/pull/14775/, https://github.com/opensearch-project/OpenSearch/pull/14735, https://github.com/opensearch-project/OpenSearch/pull/14709

2024-10-29 23:58 UTC, ruai0511 commented
Workload Management plugin is only available in 2.17.0, but when I use the default ${OPENSEARCH_VERSION:-latest} in docker-compose file, it only gives 2.14.0. So I hardcoded 2.17.0 in it. I'm wondering if there's any cleaner ways of doing it?

2024-10-30 09:10 UTC, dblock requested changes
Thanks!

The docker compose in `tests/plugins/wlm` is identical to the default one. We do custom `plugins/xyz` for when additional setup is required, so move this into `tests/default` and you don't need a special entry in the CI matrix.

2024-10-30 09:10 UTC, dblock commented on spec/namespaces/query_group.yaml
> +openapi: 3.1.0
I think this should be `wlm.yaml` to group all WLM APIs together.

2024-10-30 09:10 UTC, dblock commented on tests/plugins/wlm/query_group/query_group.yaml
> +$schema: ../../../../json_schemas/test_story.schema.yaml
Since the API is `/_wlm/query_group` this should be in `tests/default/wlm/query_group.yaml`.

2024-10-30 19:32 UTC, ruai0511 commented
> Thanks!
> 
> The docker compose in `tests/plugins/wlm` is identical to the default one. We do custom `plugins/xyz` for when additional setup is required, so move this into `tests/default` and you don't need a special entry in the CI matrix.

The default docker compose uses ${OPENSEARCH_VERSION:-latest} which is 2.14.0, but we need 2.17.0 here

2024-10-30 19:55 UTC, dblock commented
> > Thanks!
> > The docker compose in `tests/plugins/wlm` is identical to the default one. We do custom `plugins/xyz` for when additional setup is required, so move this into `tests/default` and you don't need a special entry in the CI matrix.
> 
> The default docker compose uses ${OPENSEARCH_VERSION:-latest} which is 2.14.0, but we need 2.17.0 here. That's why I put the tests in plugin since we need Dockerfile (to install the workload-management plugin) and docker compose with version 2.17.0

You should upgrade that number, and it's 2.17 in CI: https://github.com/opensearch-project/opensearch-api-specification/blob/main/.github/workflows/test-spec.yml

2024-10-30 20:49 UTC, ruai0511 commented
> > > Thanks!
> > > The docker compose in `tests/plugins/wlm` is identical to the default one. We do custom `plugins/xyz` for when additional setup is required, so move this into `tests/default` and you don't need a special entry in the CI matrix.
> > 
> > 
> > The default docker compose uses ${OPENSEARCH_VERSION:-latest} which is 2.14.0, but we need 2.17.0 here. That's why I put the tests in plugin since we need Dockerfile (to install the workload-management plugin) and docker compose with version 2.17.0
> 
> You should upgrade that number, and it's 2.17 in CI: https://github.com/opensearch-project/opensearch-api-specification/blob/main/.github/workflows/test-spec.yml

wlm is not installed by default. So we still need a separate dockerfile to install it.

2024-10-30 21:09 UTC, dblock commented
> > > > Thanks!
> > > > The docker compose in `tests/plugins/wlm` is identical to the default one. We do custom `plugins/xyz` for when additional setup is required, so move this into `tests/default` and you don't need a special entry in the CI matrix.
> > > 
> > > 
> > > The default docker compose uses ${OPENSEARCH_VERSION:-latest} which is 2.14.0, but we need 2.17.0 here. That's why I put the tests in plugin since we need Dockerfile (to install the workload-management plugin) and docker compose with version 2.17.0
> > 
> > 
> > You should upgrade that number, and it's 2.17 in CI: https://github.com/opensearch-project/opensearch-api-specification/blob/main/.github/workflows/test-spec.yml
> 
> wlm is not installed by default. So we still need a separate dockerfile to install it and it should be in the plugins directory

Sorry to be a pest, the plugin is called `workload-management` not `wlm` so let's make the folder `tests/plugins/workload-management`? The namespace is correct, since the route is `wlm`.

2024-10-30 21:23 UTC, dblock approved these changes
Good work! Thanks for hanging in here with me.

2024-10-30 21:23 UTC, merged

2024-10-30 22:45 UTC, dblock commented on CHANGELOG.md
> +- Added API specs for query groups lifecycle APIs ([#649](https://github.com/opensearch-project/opensearch-api-specification/pull/649))
@ruai0511 I missed this, but we released 0.1.0, could you please move this in another PR to the unreleased section? thanks