adding tests for search templates
opensearch-project/opensearch-api-specification pull request #702
Opened 2024-12-01 08:37 UTC by Tokesh

### Description
test for:
GET /{index}/_search/template
POST /{index}/_search/template
GET /_search/template
POST /_search/template

### Issues Resolved
[#663]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-01 13:25 UTC, dblock requested changes
Looks good, do add to CHANGELOG.

2024-12-01 13:25 UTC, dblock commented on spec/namespaces/_core.yaml
> +              status:
This should go into CHANGELOG in fixes as "Added missing `status` to `/_search/template` response"

2024-12-02 16:38 UTC, Tokesh commented
@dblock ready for your review!

2024-12-02 17:47 UTC, Tokesh commented
> Sorry to be annoying. Let's put these tests in the right place?
> 
> `/{index}/_search/template` -> `tests/default/indices/search/template.yaml` `/_search/template` -> `tests/default/search/template.yaml`

Its doesn't annoying! Thank you

2024-12-02 19:11 UTC, dblock approved these changes

2024-12-02 19:11 UTC, merged