Added test for `POST /{index}/_mapping`
opensearch-project/opensearch-api-specification pull request #745
Opened 2024-12-17 19:25 UTC by Tokesh

### Description
 POST /{index}/_mapping

### Issues Resolved
[#663]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-17 19:28 UTC, Tokesh commented
Dont merge this PR please! :)

2024-12-18 16:59 UTC, dblock approved these changes

2024-12-18 17:01 UTC, dblock requested changes
Small ask.

2024-12-18 17:01 UTC, dblock commented on tests/default/indices/mapping/index.yaml
> +  - synopsis: Add or update mapping using POST method.
This is a bit redundant with what's above. Change the first `PUT /{index}/_mapping` to having two verbs, `PUT` and `POST`.

2024-12-18 17:20 UTC, dblock approved these changes

2024-12-18 17:20 UTC, merged