adding missing tests
opensearch-project/opensearch-api-specification pull request #749
Opened 2024-12-18 17:57 UTC by Tokesh

### Description
 DELETE /_search/scroll
 POST /_snapshot/{repository}/{snapshot}
 POST /_update_by_query/{task_id}/_rethrottle
 PUT /_wlm/query_group/{name}

### Issues Resolved
[#663 ]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-18 20:14 UTC, dblock requested changes
Some asks below.

Throw a retry into the flaky snapshot test.

2024-12-18 20:14 UTC, dblock commented on tests/default/_core/update_by_query.yaml
> +$schema: ../../../json_schemas/test_story.schema.yaml
This is _update_by_query/rethrottle, so it should be in `tests/default/_core/_update_by_query/rethrottle.yaml`.

2024-12-18 20:14 UTC, dblock commented on tests/default/_core/update_by_query.yaml
> +description: Test Update By Query endpoint.
```suggestion
description: Test Update By Query rethrottle endpoint.
```

2024-12-18 20:14 UTC, dblock commented on tests/default/_core/update_by_query.yaml
> +  - path: /books/_delete_by_query
Should this be trying to do an `update_by_query` and not a `_delete_by_query`?

2024-12-18 20:14 UTC, dblock commented on tests/snapshot/snapshot/snapshot.yaml
> -      repository: my-fs-repository
We have a bunch of tests where we say `my-fs-repository`, either change them all or change this back to `my-fs-repository`.

2024-12-19 09:54 UTC, Tokesh commented
> Some asks below.
> 
> Throw a retry into the flaky snapshot test.

Thank you! Ready for your review

2024-12-19 13:31 UTC, dblock approved these changes

2024-12-19 13:31 UTC, merged